### ISSUE TITLE
初始化脚本是否可以提供

### ISSUE THREAD

**Issue by sampsongi** [jimmyzhong/sofa-dashboard#3]
您好！同事推荐您开发的这款项目，研究之后确实写得不错，就是数据表设计比较复杂，请问能否提供登录的初始化脚本以供进一步测试试用，谢谢！

**Comment by jimmyzhong** [comment]
初始数据在 sofa-admin/sofa-admin-bootstrap/src/main/txt/data
帐号admin 密码 admin123
